_target_: i2rt.robots.motor_chain_robot.MotorChainRobot
motor_chain:
  _target_: i2rt.motor_drivers.dm_driver.DMChainCanInterface
  motor_list:
    - [0x01, "DM4340"]
    - [0x02, "DM4340"]
    - [0x03, "DM4340"]
    - [0x04, "DM4310"]
    - [0x05, "DM4310"]
    - [0x06, "DM4310"]
    - [0x07, "DM4310"]
  motor_offset: [0, 0, 0, 0, 0, 0, 0]
  motor_direction: [1, 1, 1, 1, 1, 1, 1]
  channel: "can0"
  # channel: "can_follow_l"
  motor_chain_name: "yam_left"
  receive_mode:
    _target_: i2rt.motor_drivers.dm_driver.ReceiveMode
    value: "p16"
xml_path: "dependencies/i2rt/i2rt/robot_models/yam/yam.xml"
gravity_comp_factor: 1.3
gripper_index: 6
# repo values
# kp: [80, 80, 80, 10, 10, 10, 20]
# kd: [5, 5, 5, 1.5, 1.5, 1.5, 0.5]
# joint_limits:
#   - [-2.09, 3.14]
#   - [0, 3.14]
#   - [0.05, 3.14]
#   - [-1.35, 1.35]
#   - [-1.50, 1.50]
#   - [-2.00, 2.00]
# gripper_limits: [0.0, -2.4] # a smaller opening, full opening is -2.7

# i2rt default values
kp: [80, 80, 80, 40, 10, 10, 20]
kd: [5, 5, 5, 1.5, 1.5, 1.5, 0.5]

# 10, 1.9
# 20, 2.2
# kp: [80, 80, 80, 10, 10, 10, 20]
# kd: [5, 5, 5, 1.5, 1.5, 1.6, 0.5]


joint_limits:
  - [-2.767, 3.28]
  - [-0.15, 3.80]
  - [-0.15, 3.28]
  - [-1.72, 1.72]
  - [-1.72, 1.72]
  - [-2.24, 2.24]
gripper_limits: [0.0, -2.7] 
limit_gripper_force: 50.0
# gripper_type: "yam_small"
